### ISSUE TITLE
I've uploaded all the classwork and assignments. My name isn't there in the assessment matrix. Please add me.

### ISSUE THREAD

**Issue by Anavi6** [grvashu/srishti-digital-interfaces#4]

**Comment by grvashu** [comment]
Done. You are added now.

**Comment by grvashu** [comment]
Your programs aren't working. Please check.

**Comment by Anavi6** [comment]
They are working on my laptop. Maybe i could show them in class on Tuesday?

**Comment by grvashu** [comment]
Your programs were not working due to missing p5.js file.

Please follow the correct way to structure your directory as instructed.
Please upload a folder A1 containing assignment for week 1. It should contain a html file, js file and p5.js file. Do same for week 2 and name it A2. Upload another folder classwork if you want to upload any classwork problems.

**Comment by RebeccaMathew** [comment]
hi there!

even im not there in the assignment matrix. please add me. 
thank you

**Comment by grvashu** [comment]
Done. You are added.

**Comment by Divyaprabhaj** [comment]
Divya here!
My name is not added in the assessment matrix. pls add me too.

**Comment by grvashu** [comment]
Done.

**Comment by grvashu** [comment]
@Anavi6 Checked your new files. Please make sure that p5.js is linked properly. Your HTML file contains `<script language="javascript" type="text/javascript" src="libraries/p5.js"></script>` while your assignment directory does not contain any libraries folder.

The js file in A2 also contains syntactical errors other than the above problem.

**Comment by PP3001** [comment]
Hey, i was unable to attend classes last week due to some health problem, my name isnt up on the assessment matrix either.
